<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>orion_gz_plugins</name>
  <version>0.1.0</version>
  <description>GZ Harmonic plugins for ORION: emotion display screen and touch sensors</description>
  <maintainer email="dfelipe.lopez@gmail.com">DanielFLopez1620</maintainer>
  <license>BSD 3 Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>ament_index_cpp</build_depend>
  <build_depend>gz-transport13</build_depend>
  <build_depend>gz-msgs10</build_depend>
  <build_depend>gz-plugin2</build_depend>
  <build_depend>gz-gui8</build_depend>
  <build_depend>gz-rendering8</build_depend>
  <build_depend>gz-common5</build_depend>

  <exec_depend>ament_index_cpp</exec_depend>
  <exec_depend>gz-transport13</exec_depend>
  <exec_depend>gz-msgs10</exec_depend>
  <exec_depend>gz-gui8</exec_depend>
  <exec_depend>gz-rendering8</exec_depend>
  <exec_depend>gz-common5</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
